### Terms Related to Data Clearning
* **Data cleaning**: Process of detecting, diagnosing, and editing faulty data
* **Data editing**: Chaning the value of data shown to be incorrect
* **Data flow**: Passage of recorded information through successive information carriers
* **Inlier**: Data value falling within the expected range
* **Outlier**: Data value falling outside the expected range
* **Robust estimation**: Estimation of statistical parameters, using methods that are less sensitive to the effect of outliers than more conventional methods

### Quality Assurance Process
* error prevention
* data monitoring
* data clearning
* documentation

### Data Cleaning
Data clearning is a three-stage process, which includes repeated cycles of screening, diagnosing, and editing of suspected data abnormalities. It must be based on the knowledge of technical errors and expected ranges of normal values.

### Priority of Errors
Errors should be taken care of at different priorities, where the priorities are highly study-specific. In medical research, errors of sex and date are particularly important becase they contaminate derived vriables.

### Oddities
Oddities in screening phase are
* Lack or excess of data
* Outliers(including inconsistencies)
* Strange patterns in distributions
* unexpected analysis results
* erroneous inliers(data points generated by error but falling within the expected range)


### Acknowledgement
This is a abstract from the article [Data Cleaning: Detecting, Diagnosing, and Editing Data Abnormalities](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.0020267)

